%YAML 1.2
---

# host infos
host_string: '10.73.73.105'
host_port: '9090'
host_user: 'root'
host_pass: 'redhat'

# manually configured selenium hub
selenium_hub: ''

# avocado config
avocado_results_dir: '/home/weiwang/work_auto/avocado-results'

# versions of pkg/sys under test
test_pkg_ver: 'cockpit-ovirt-dashboard-0.14.17-1'
test_sys_ver: 'rhvh-4.4.4.2-0.20210307.0'

